# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Adrián García-Gutiérrez
title: Lecturer
email: a.gutierrez@unileon.es
website: uleia.unileon.es

# Dark Mode (true/false/never)
darkmode: false

# Social links
# Social links
#twitter_username: facespics
github_username:  garcgutierrez
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: jameswgrant
linkedin_username: adrián-garcía-gutiérrez-621945248
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
orcid_username: 0000-0001-6790-3907

# Additional icon links
additional_links:
- title: PortalCientífico
  icon: fab fa-trello
  url: https://portalcientifico.unileon.es/investigadores/97473/detalle
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Adrián, and I'm a lecturer at the University of León. I teach courses in Aerodynamics, Helicopters, and Computational Fluid Dynamics as part of the Aerospace Engineering degree program. I’ve also had the opportunity to participate in research projects with some of the most prominent companies in the aerospace sector, including Boeing, GMV, and Indra.
  My research focuses on <mark>CFD</mark>, <mark>low Reynolds Number Aerodynamics</mark>, and <mark>Stochastic Design</mark>.


content:
  - title: Papers # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: On the capabilities and limitations of high altitude pseudo-satellites
        link: doi.org/10.1016/j.paerosci.2018.03.006
        link_text: Link
        description: | # this will include new lines to allow paragraphs
          The idea of self-sustaining air vehicles that excited engineers in the seventies has nowadays become a reality as proved by several initiatives worldwide. High altitude platforms, or Pseudo-satellites (HAPS), are unmanned vehicles that take advantage of weak stratospheric winds and solar energy to operate without interfering with current commercial aviation and with enough endurance to provide long-term services as satellites do. Target applications are communications, Earth observation, positioning and science among others. This paper reviews the major characteristics of stratospheric flight, where airplanes and airships will compete for best performance. The careful analysis of involved technologies and their trends allow budget models to shed light on the capabilities and limitations of each solution. Aerodynamics and aerostatics, structures and materials, propulsion, energy management, thermal control, flight management and ground infrastructures are the critical elements revisited to assess current status and expected short-term evolutions. Stratospheric airplanes require very light wing loading, which has been demonstrated to be feasible but currently limits their payload mass to few tenths of kilograms. On the other hand, airships need to be large and operationally complex but their potential to hover carrying hundreds of kilograms with reasonable power supply make them true pseudo-satellites with enormous commercial interest. This paper provides useful information on the relative importance of the technology evolutions, as well as on the selection of the proper platform for each application or set of payload requirements. The authors envisage prompt availability of both types of HAPS, aerodynamic and aerostatic, providing unprecedented services.
      - layout: left
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: Uncertainty quantification study of the aerodynamic performance of high-altitude propellers
        link: https://doi.org/10.1016/j.ast.2023.108108
        link_text: Link
        description: | # this will include new lines to allow paragraphs
          Performance evaluations for propellers operating at high altitudes are subject to increased uncertainty due to scarce experimental or flight data and difficulties in modeling low Reynolds number flows. For this reason, the Polynomial Chaos Expansion (PCE) method is used in this paper to assess the performance uncertainty of propellers operating at high altitudes. Aleatoric (i.e. linked to the geometry or operating conditions) and epistemic (i.e. linked to the mathematical model describing the flow) uncertainty variables are included in this study to estimate the total uncertainty related to performance predictions made by two physical models, namely 3D RANS with the use of transition model and Blade Element Momentum Theory (BEMT). In order to validate the proposed method, multipoint uncertainty quantification (UQ) studies are performed for two benchmark propeller geometries under various operating conditions for which experimental data are available. The UQ method is further illustrated on a propeller operating at high altitude. The efficacy of UQ with Computational Fluid Dynamics (CFD) and BEMT is compared and the most influential uncertain variables are found using Sobol's total order indices. As a result of the CFD-based uncertainty quantification studies, two major uncertain variables are identified, providing a direction for more computationally affordable UQ studies.
      - layout: left
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: A low-storage method consistent with second-order statistics for time-resolved databases of turbulent channel flow up to Re_tau = 5300
        link: https://doi.org/10.1016/j.jocs.2021.101476
        link_text: Link
        description: | # this will include new lines to allow paragraphs
          Wall-bounded flows play an important role in numerous common applications, and have been intensively studied for over a century. However, the dynamics and structure of the logarithmic and outer regions remain controversial to this date, and understanding their dynamics is essential for the development of effective prediction and control strategies, and for the construction of a complete theory of wall-bounded flows. Recently, the use of time-resolved direct numerical simulations of turbulent flows at high Reynolds numbers has proved useful to study the physics of wall-bounded turbulence, but a proper analysis of the logarithmic and outer layers requires simulations at high Reynolds numbers in large domains, making the storage of complete time series challenging. In this paper a novel low-storage method for time-resolved databases is presented. This approach reduces the storage cost of time-resolved databases by storing filtered flow fields that target the large and intermediate scales, while retaining all the information needed to fully reconstruct the flow at the level of filtered flow fields and complete second-order statistics. This is done by storing also the filtered turbulent stresses, allowing to recover the exact effect of the small scales on the large and intermediate scales. A significant speed-up of the computations is achieved, first, by relaxing the numerical resolution, which is shown to affect only the dynamics close to the wall, but not the large scales stored in the database, and, second, by exploiting the computing power and efficiency of GPU co-processors using a new high-resolution hybrid CUDA-MPI code. This speed-up allows running for physically meaningful times to capture the dynamics of the large scales. The resulting temporally resolved large-scale database of a turbulent channel flow up to Re_tau = 5300, in large boxes for long times, is briefly introduced, showing significant indicators of large-scale dynamics with characteristic times of the order of up to eight eddy turnover times.
      - layout: left
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: Estimating Landfill Landslide Probability Using SAR Satellite Products
        link: mdpi.com/2072-4292/16/9/1618
        link_text: Link
        quote: >
          The research leading to these results received funding from the European Space Agency under the Contract No. 4000138806/22/I-DT-bgh (EOP—Future EO Open Call for Proposals).
        description: | # this will include new lines to allow paragraphs
          This article presents a methodology for evaluating the susceptibility of landfill areas to develop landslides by analyzing Synthetic Aperture Radar (SAR) satellite products. The deformation velocity of the landfills is computed through the Persistent Scatterer Method on SAR imagery. These data, combined with a deformation model based on the shallow water equations (SWE), form the foundation for a Monte Carlo experiment that extrapolates the current state of the landfill into the future. The results of this simulation are then employed to determine the probability of a landslide occurrence. In order to validate the methodology effectiveness, a case study is conducted on a landfill in Zaldibar, Spain, revealing its effectiveness in estimating the probability of landfill landslides. This innovative approach emerges as an asset in large landfill management, acting as a proactive tool for identifying high-risk sites and preventing potential landslides, ultimately safeguarding human life and the environment. By providing insights into landslide probabilities, this study enhances decision-making processes and facilitates the development of intervention strategies in the domain of landfill risk assessment and management.
          
  - title: Education
    layout: list
    content:
      - layout: top-right
        title: PhD Engineering
        sub_title: University of León
        caption: 2020
      - layout: top-left
        title: MSc Physics of Complex Systems
        sub_title: UNED
        caption: 2023
      - layout: top-right
        title: MSc Space Systems
        sub_title: Technical University of Madrid
        caption: 2015-2017        
        #quote: >
        #  Short institution or course description (optional)
        #description: | # this will include new lines to allow paragraphs
        #  Description of qualification
      - layout: top-left
        title: BSc Aerospace Science
        sub_title: University of León
        caption: 2011 - 2015
        #quote: >
        #  Short institution or course description (optional)
        #description: | # this will include new lines to allow paragraphs
        #  Description of qualification
          
      - layout: top-right
        title: BSc Mathematics
        sub_title: UNED
        caption: 2016 - 2020
        #quote: >
        #  Short institution or course description (optional)
        #description: | # this will include new lines to allow paragraphs
        #  Description of qualification
 
# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
