# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 3

# Personal info
name: Adrián García-Gutiérrez
title: Lecturer
email: a.gutierrez@unileon.es
website: uleia.unileon.es

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: facespics
github_username:  garcgutierrez
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: jameswgrant
linkedin_username: adrián-garcía-gutiérrez-621945248
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
orcid_username: 0000-0001-6790-3907

# Additional icon links
additional_links:
- title: PortalCientífico
  icon: fab fa-trello
  url: https://portalcientifico.unileon.es/investigadores/97473/detalle

# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Adrián, and I'm a lecturer at the University of León. I teach courses in Aerodynamics, Helicopters, and Computational Fluid Dynamics as part of the Aerospace Engineering degree program. I’ve also had the opportunity to participate in research projects with some of the most prominent companies in the aerospace sector, including Boeing, GMV, and Indra.
  My research focuses on Computational Fluid Dynamics (<mark>CFD</mark>), <mark>low Reynolds number aerodynamics</mark>, and <mark>stochastic design</mark>.

content:
  - title: Papers # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: On the capabilities and limitations of high altitude pseudo-satellites
        link: doi.org/10.1016/j.paerosci.2018.03.006
        # link_text: Project Website
        description: | # this will include new lines to allow paragraphs
          The idea of self-sustaining air vehicles that excited engineers in the seventies has nowadays become a reality as proved by several initiatives worldwide. High altitude platforms, or Pseudo-satellites (HAPS), are unmanned vehicles that take advantage of weak stratospheric winds and solar energy to operate without interfering with current commercial aviation and with enough endurance to provide long-term services as satellites do. Target applications are communications, Earth observation, positioning and science among others. This paper reviews the major characteristics of stratospheric flight, where airplanes and airships will compete for best performance. The careful analysis of involved technologies and their trends allow budget models to shed light on the capabilities and limitations of each solution. Aerodynamics and aerostatics, structures and materials, propulsion, energy management, thermal control.

        


# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
